services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csv_server
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata
    env_file:
      - csvserver.env
