services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csv_server
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata
    env_file:
      - csvserver.env

  prometheus:
    image: prom/prometheus:v2.45.2
    container_name: prometheus
    volumes:
      - /Users/amird/csvserver/solution/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

